// Named-color dictionary — finds the closest English color name for any RGB.
// Lookup is in CIE Lab space for perceptual nearest-neighbor.

import type { RGB } from "@/types";
import { hexToRgb, rgbToLab } from "./color";

interface NamedEntry { name: string; hex: string; lab: [number, number, number] }

const RAW: { name: string; hex: string }[] = [
  // ----- Achromatic / neutrals -----
  { name: "Pitch", hex: "#000000" },
  { name: "Onyx", hex: "#0a0a0a" },
  { name: "Ink", hex: "#13141a" },
  { name: "Coal", hex: "#1c1c1c" },
  { name: "Soot", hex: "#26252a" },
  { name: "Graphite", hex: "#2a2a2a" },
  { name: "Charcoal", hex: "#36454f" },
  { name: "Smoke", hex: "#4a4d4f" },
  { name: "Slate", hex: "#708090" },
  { name: "Pewter", hex: "#8a8d91" },
  { name: "Steel Grey", hex: "#7d8085" },
  { name: "Iron", hex: "#5a5d62" },
  { name: "Concrete", hex: "#a3a3a0" },
  { name: "Stone", hex: "#998d80" },
  { name: "Ash", hex: "#b2beb5" },
  { name: "Dove", hex: "#cfcdc3" },
  { name: "Pearl", hex: "#eaeaea" },
  { name: "Silver", hex: "#c0c0c0" },
  { name: "Mist", hex: "#d6d4d0" },
  { name: "Fog", hex: "#dcdfe1" },
  { name: "Linen", hex: "#faf0e6" },
  { name: "Eggshell", hex: "#f0ead6" },
  { name: "Ivory", hex: "#fffff0" },
  { name: "Vellum", hex: "#fff8dc" },
  { name: "Cream", hex: "#fffdd0" },
  { name: "Bone", hex: "#e3dac9" },
  { name: "Marble", hex: "#f6f3ee" },
  { name: "Snow", hex: "#fffafa" },
  { name: "Porcelain", hex: "#f0eee8" },
  { name: "Chalk", hex: "#e6e2dc" },
  { name: "Paper", hex: "#f7f4ec" },
  { name: "White", hex: "#ffffff" },

  // ----- Browns / earth / wood -----
  { name: "Beige", hex: "#f5f5dc" },
  { name: "Almond", hex: "#efdecd" },
  { name: "Wheat", hex: "#f5deb3" },
  { name: "Champagne", hex: "#f7e7ce" },
  { name: "Sand", hex: "#c2b280" },
  { name: "Buff", hex: "#dab886" },
  { name: "Tan", hex: "#d2b48c" },
  { name: "Khaki", hex: "#c3b091" },
  { name: "Camel", hex: "#c19a6b" },
  { name: "Caramel", hex: "#a47148" },
  { name: "Nutmeg", hex: "#8e5a3a" },
  { name: "Cinnamon", hex: "#a0522d" },
  { name: "Hazel", hex: "#8e7037" },
  { name: "Walnut", hex: "#5d4037" },
  { name: "Mahogany", hex: "#4a2818" },
  { name: "Chocolate", hex: "#5d3a1a" },
  { name: "Mocha", hex: "#7c5544" },
  { name: "Coffee", hex: "#6f4e37" },
  { name: "Espresso", hex: "#3b2a20" },
  { name: "Cocoa", hex: "#3a1f0e" },
  { name: "Chestnut", hex: "#954535" },
  { name: "Tawny", hex: "#cd5700" },
  { name: "Sepia", hex: "#704214" },
  { name: "Bistre", hex: "#3d2b1f" },
  { name: "Umber", hex: "#635147" },
  { name: "Burnt Umber", hex: "#8a3324" },
  { name: "Sienna", hex: "#a0522d" },
  { name: "Burnt Sienna", hex: "#e97451" },
  { name: "Rust", hex: "#b7410e" },
  { name: "Patina", hex: "#7d8a78" },
  { name: "Verdigris", hex: "#43b3ae" },
  { name: "Brick", hex: "#9b3a3a" },
  { name: "Terracotta", hex: "#cb6843" },
  { name: "Clay", hex: "#b66a50" },
  { name: "Adobe", hex: "#a47551" },
  { name: "Driftwood", hex: "#a8917c" },
  { name: "Birch", hex: "#dac9a6" },
  { name: "Oak", hex: "#806043" },
  { name: "Pine", hex: "#5a4128" },
  { name: "Mushroom", hex: "#9c8a7a" },
  { name: "Taupe", hex: "#9b8b80" },
  { name: "Mauve Taupe", hex: "#915f6d" },
  { name: "Khaki Drab", hex: "#7a6b3a" },

  // ----- Reds / wines / pinks -----
  { name: "Wine", hex: "#722f37" },
  { name: "Bordeaux", hex: "#5c1e1e" },
  { name: "Burgundy", hex: "#570404" },
  { name: "Maroon", hex: "#800000" },
  { name: "Oxblood", hex: "#4a0d0d" },
  { name: "Garnet", hex: "#7a1f1f" },
  { name: "Carmine", hex: "#960018" },
  { name: "Crimson", hex: "#dc143c" },
  { name: "Cardinal", hex: "#c41e3a" },
  { name: "Cherry", hex: "#cc2a3d" },
  { name: "Ruby", hex: "#b3203b" },
  { name: "Vermilion", hex: "#e34234" },
  { name: "Cinnabar", hex: "#e34234" },
  { name: "Red", hex: "#e63946" },
  { name: "Scarlet", hex: "#ff2400" },
  { name: "Tomato", hex: "#ff6347" },
  { name: "Coral", hex: "#ff7f50" },
  { name: "Salmon", hex: "#fa8072" },
  { name: "Persimmon", hex: "#ec5800" },
  { name: "Watermelon", hex: "#fc6c85" },
  { name: "Bubblegum", hex: "#ffc1cc" },
  { name: "Cotton Candy", hex: "#ffbcd9" },
  { name: "Pink", hex: "#ffc0cb" },
  { name: "Blush", hex: "#de5d83" },
  { name: "Rose", hex: "#ff66cc" },
  { name: "Tea Rose", hex: "#f4c2c2" },
  { name: "Dusty Rose", hex: "#dcae96" },
  { name: "Mauve", hex: "#e0b0ff" },
  { name: "Fuchsia", hex: "#ff00ff" },
  { name: "Magenta", hex: "#c2185b" },
  { name: "Raspberry", hex: "#e30b5c" },
  { name: "Hot Pink", hex: "#ff69b4" },
  { name: "Flamingo", hex: "#fc8eac" },
  { name: "Peony", hex: "#e84e7d" },
  { name: "Pomegranate", hex: "#a83232" },

  // ----- Purples / violets / lavenders -----
  { name: "Plum", hex: "#8e4585" },
  { name: "Aubergine", hex: "#3d0734" },
  { name: "Eggplant", hex: "#614051" },
  { name: "Lavender", hex: "#b497d6" },
  { name: "Lilac", hex: "#c8a2c8" },
  { name: "Heather", hex: "#b283a4" },
  { name: "Wisteria", hex: "#c9a0dc" },
  { name: "Periwinkle", hex: "#ccccff" },
  { name: "Orchid", hex: "#da70d6" },
  { name: "Iris", hex: "#5a4fcf" },
  { name: "Amethyst", hex: "#9966cc" },
  { name: "Violet", hex: "#8a2be2" },
  { name: "Mulberry", hex: "#771f5d" },
  { name: "Boysenberry", hex: "#873260" },
  { name: "Purple", hex: "#6a0dad" },
  { name: "Royal Purple", hex: "#7851a9" },
  { name: "Imperial", hex: "#5e003d" },
  { name: "Tyrian", hex: "#66023c" },
  { name: "Indigo", hex: "#4b0082" },
  { name: "Twilight", hex: "#3a2e5d" },
  { name: "Midnight", hex: "#191970" },

  // ----- Blues -----
  { name: "Royal Blue", hex: "#4169e1" },
  { name: "Sapphire", hex: "#0f52ba" },
  { name: "Cobalt", hex: "#0047ab" },
  { name: "Yves Klein", hex: "#002fa7" },
  { name: "Ultramarine", hex: "#3f00ff" },
  { name: "Lapis", hex: "#26619c" },
  { name: "Navy", hex: "#1a2752" },
  { name: "Prussian", hex: "#003153" },
  { name: "Steel Blue", hex: "#4682b4" },
  { name: "Denim", hex: "#1560bd" },
  { name: "Cornflower", hex: "#6495ed" },
  { name: "Powder Blue", hex: "#b0e0e6" },
  { name: "Robin's Egg", hex: "#73c2fb" },
  { name: "Sky", hex: "#87ceeb" },
  { name: "Cerulean", hex: "#007ba7" },
  { name: "Azure", hex: "#a3d8f4" },
  { name: "Cornflower Blue", hex: "#5170c5" },
  { name: "Blue", hex: "#0a66dd" },
  { name: "Ice", hex: "#d6ecf2" },
  { name: "Glacier", hex: "#80b3c4" },
  { name: "Periwinkle Blue", hex: "#8896d6" },
  { name: "Slate Blue", hex: "#6a5acd" },

  // ----- Cyan / teal -----
  { name: "Cyan", hex: "#00b7c2" },
  { name: "Aqua", hex: "#7fffd4" },
  { name: "Tiffany", hex: "#0abab5" },
  { name: "Turquoise", hex: "#40e0d0" },
  { name: "Lagoon", hex: "#5e92a8" },
  { name: "Teal", hex: "#008080" },
  { name: "Pine Teal", hex: "#3a716a" },
  { name: "Aquamarine", hex: "#7fffd4" },
  { name: "Seafoam", hex: "#9fe2bf" },
  { name: "Mint", hex: "#98e0b6" },
  { name: "Spearmint", hex: "#92cc94" },
  { name: "Jade", hex: "#00a86b" },
  { name: "Celadon", hex: "#ace1af" },
  { name: "Eucalyptus", hex: "#5b9279" },
  { name: "Ocean", hex: "#1a5278" },
  { name: "Marine", hex: "#013a63" },
  { name: "Peacock", hex: "#005f6a" },

  // ----- Greens -----
  { name: "Sage", hex: "#9caf88" },
  { name: "Pistachio", hex: "#93c572" },
  { name: "Olive", hex: "#808000" },
  { name: "Olive Drab", hex: "#6b8e23" },
  { name: "Moss", hex: "#5a6b3b" },
  { name: "Fern", hex: "#71a05c" },
  { name: "Forest", hex: "#1f5132" },
  { name: "Hunter", hex: "#355e3b" },
  { name: "Pine Green", hex: "#01796f" },
  { name: "Juniper", hex: "#3c5e4b" },
  { name: "Avocado", hex: "#568203" },
  { name: "Emerald", hex: "#2f8b53" },
  { name: "Kelly Green", hex: "#4cbb17" },
  { name: "Shamrock", hex: "#009e60" },
  { name: "Green", hex: "#3a8b40" },
  { name: "Apple", hex: "#8db600" },
  { name: "Lime", hex: "#8fcb46" },
  { name: "Chartreuse", hex: "#7fff00" },
  { name: "Acid Green", hex: "#b0bf1a" },
  { name: "Bottle Green", hex: "#006a4e" },
  { name: "Loden", hex: "#76734d" },

  // ----- Yellows / golds -----
  { name: "Yellow", hex: "#ffd60a" },
  { name: "Lemon", hex: "#fff44f" },
  { name: "Banana", hex: "#fce883" },
  { name: "Butter", hex: "#fff1b6" },
  { name: "Daffodil", hex: "#ffff31" },
  { name: "Canary", hex: "#ffef00" },
  { name: "Sunshine", hex: "#ffd900" },
  { name: "Jasmine", hex: "#f8de7e" },
  { name: "Honey", hex: "#dfa54c" },
  { name: "Mustard", hex: "#d4a83a" },
  { name: "Dijon", hex: "#9b7f2c" },
  { name: "Saffron", hex: "#f4c430" },
  { name: "Marigold", hex: "#eaa221" },
  { name: "Goldenrod", hex: "#daa520" },
  { name: "Gold", hex: "#d4a017" },
  { name: "Bronze", hex: "#cd7f32" },
  { name: "Brass", hex: "#b5a642" },
  { name: "Citrine", hex: "#e4d00a" },
  { name: "Amber", hex: "#ffbf00" },
  { name: "Topaz", hex: "#ffc87c" },

  // ----- Oranges -----
  { name: "Apricot", hex: "#fbceb1" },
  { name: "Peach", hex: "#ffd0a8" },
  { name: "Cantaloupe", hex: "#ffa177" },
  { name: "Papaya", hex: "#ffefd5" },
  { name: "Mango", hex: "#ffae42" },
  { name: "Tangerine", hex: "#f28500" },
  { name: "Pumpkin", hex: "#ff7518" },
  { name: "Orange", hex: "#ff7a00" },
  { name: "Carrot", hex: "#ed9121" },
  { name: "Persimmon", hex: "#ec5800" },
  { name: "Copper", hex: "#b87333" },
  { name: "Burnt Orange", hex: "#cc5500" },
  { name: "Henna", hex: "#a14a3a" },
  { name: "Ochre", hex: "#c89c4c" },
  { name: "Yellow Ochre", hex: "#ce8e00" },
  { name: "Mars Yellow", hex: "#cd853f" },

  // ----- Specialty / cultural / poetic -----
  { name: "Tobacco", hex: "#7e482d" },
  { name: "Saddle", hex: "#8b4513" },
  { name: "Rosewood", hex: "#65000b" },
  { name: "Cedar", hex: "#5e4732" },
  { name: "Bark", hex: "#5b3924" },
  { name: "Antique", hex: "#faebd7" },
  { name: "Heirloom", hex: "#a89f74" },
  { name: "Vintage", hex: "#cdaa7d" },
  { name: "Manuscript", hex: "#dfd2af" },
  { name: "Silk", hex: "#fcf5e5" },
  { name: "Parchment", hex: "#f1e9d2" },
  { name: "Honeydew", hex: "#f0fff0" },
  { name: "Moonstone", hex: "#bbd4d8" },
  { name: "Pearl Pink", hex: "#fadadd" },
  { name: "Champagne Pink", hex: "#f1ddcf" },
  { name: "Nude", hex: "#e3bc9a" },
  { name: "Cocoa Pink", hex: "#dba0a3" },
  { name: "Old Rose", hex: "#c08081" },
  { name: "Tea Green", hex: "#d0f0c0" },
  { name: "Bottle", hex: "#063b27" },
  { name: "Asparagus", hex: "#87a96b" },
  { name: "Pickle", hex: "#5d6d3a" },
  { name: "Artichoke", hex: "#8f9779" },
  { name: "Olivine", hex: "#9ab973" },
  { name: "Gunmetal", hex: "#2a3439" },
  { name: "Charcoal Blue", hex: "#36454f" },
  { name: "Slate Indigo", hex: "#3a4566" },
];

const NAMED_LAB: NamedEntry[] = RAW.map(({ name, hex }) => {
  const [r, g, b] = hexToRgb(hex);
  return { name, hex, lab: rgbToLab(r, g, b) };
});

export function nameForRGB(rgb: RGB): string {
  const [tL, tA, tB] = rgbToLab(...rgb);
  let best = NAMED_LAB[0];
  let bestD = Infinity;
  for (const n of NAMED_LAB) {
    const [L, A, B] = n.lab;
    const d = (L - tL) ** 2 + (A - tA) ** 2 + (B - tB) ** 2;
    if (d < bestD) { bestD = d; best = n; }
  }
  return best.name;
}

export function paletteLabel(L: number, chroma: number): string {
  const light = L < 25 ? "deep" : L < 50 ? "shadow" : L < 75 ? "mid" : "bright";
  const ch = chroma < 12 ? "muted" : chroma < 30 ? "soft" : "vivid";
  return `${ch} · ${light}`;
}
